## defaults for _all_ profiles
[default]
address = "0.0.0.0"
limits = { form = "64 kB", json = "1 MiB" }
template_dir = "src/resources/html"

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 8000

## set only when compiled in release mode, i.e, `cargo build --release`
[release]
port = 9999
